CREATE DATABASE ci3_feed_rss;
USE ci3_feed_rss;
 
-- Table structure for table `tbl_posts`
CREATE TABLE `tbl_posts` (
  `post_id` int(5) NOT NULL AUTO_INCREMENT,
  `post_title` varchar(100) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `post_content` longtext NOT NULL,
  `post_img` varchar(100) NOT NULL,
  `post_date` datetime NOT NULL,
  `click` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`post_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table `tbl_posts`
INSERT INTO `tbl_posts` (`post_title`, `slug`, `post_content`, `post_img`, `post_date`, `click`) VALUES
('Simple jQuery Add, Update, Delete with PHP and MySQL', 'simple-jquery-add-update-delete-with-php-and-mysql', 'Today, I want to share with you PHP Mysql CRUD using Jquery Ajax from scratch. CRUD stands for Create, Read, Update and Delete database data. Add, Edit, Update, and Delete functionality is used almost every PHP application. But today i will show you very simple way to crud using bootstrap model.<br>In this tutorial we will do insert, update and delete task for items. In this example i also use bootstrap for layout. I write just few step to follow you can make simple crud application with jquery pagination in your laravel 5 project.<br>In this example i used several jquery Plugin for fire Ajax, Ajax pagination, Bootstrap, Bootstrap Validation, notification as listed bellow.', 'img.jpg', '2019-10-01 08:04:03', 0),
('15 Free Bootstrap Admin Themes Demo and Download', '15-free-bootstrap-admin-themes-demo-and-download', 'Hallo sahabat Jendela Dunia Internet Dan Tekhnologi, Pada Artikel yang anda baca kali ini dengan judul 15 Free Bootstrap Admin Themes Demo and Download, kami telah mempersiapkan artikel ini dengan baik untuk anda baca dan ambil informasi didalamnya. mudah-mudahan isi postingan Artikel Bootstrap, Artikel Freebies, Artikel Templates, Artikel Tips, Artikel Web Design, yang kami tulis ini dapat anda pahami. baiklah, selamat membaca.', 'img.jpg', '2019-10-02 02:02:03', 0),
('Easy Ajax Image Upload with jQuery, PHP', 'easy-ajaximage-upload-with-jquery-php', 'In this blog post we have covered one of the topic of ajax i.e. to upload images using Ajax and php without page refresh.<br>In this process the image is selected first and previewed before storing it in to any location . Then using  jQuery Ajax, it is send to php script on submit button event.<br>PHP script stores the image in a defined location and returns the message of the success and failure of the process.<br>Here we have applied some validations on the selected file, to check it whether it is an image file (jpg, jpeg or png ) or any other file type.<br>Upload File size allowed is 100 Kb.', 'img.jpg', '2019-10-03 10:12:53', 0),
('How to Send HTML Format eMails in PHP using PHPMailer', 'how-to-send-html-format-emails-in-php-using-phpmailer', 'PHPMailer is a PHP class for sending email. It has far more funtionality compared to the regular mail() function, including attachments and inline images. It is very usefull for actions like \"Contactus\" forms, not allowing header injection and spamming. Supports SMTP.', 'img.jpg', '2019-10-04 17:02:12', 0),
('Ajax Bootstrap Signup Form with jQuery PHP and MySQL', 'ajax-bootstrap-signup-form-with-php-and-mysql', 'Nah sebelumnya hanya menciptakan bootstrap signup form dengan validasi dan sekarang dalam tutorial ini kita akan melihat menciptakan Bootstrap fomr dengan Ajax jQuery PHP dan<br>MySQL. Kita akan Lihat ketersediaan live email, validasi jQuery dan proses pendaftaran akan tersubmit tanpa reload halaman.<br>Sebelum melanjutkan Anda dapat memeriksa live demo tutorial ini untuk melihat bagaimana kelanjutannya, jadi mari kita mulai', 'img.jpg', '2019-10-05 12:42:03', 0),
('Submit PHP Form without Page Refresh using jQuery, Ajax', 'submit-php-form-without-page-refresh-using-jquery-ajax', 'In this tutorial, i will explain how to submit contact form without page refresh using AJAX, jQuery and PHP. We all have seen that when we submit any web form or contact form, it takes few seconds to submit without refreshing the web page.\r\n\r\nAJAX has the ability to submit form without page refresh. We will also use AJAX here along with jQuery and PHP. Although you can do anything with the form submission, in here we will send a simple email to website admin.', 'img.jpg', '2019-10-06 19:42:03', 0),
('How to Convert MySQL Rows into JSON Format in PHP', 'how-to-convert-mysql-rows-into-json-format-in-php', 'Many web applications expect external data in JSON format, hence converting MySQL data to JSON is something that web developers encounter on a regular basis. JSON (JavaScript Object Notation) is fast becoming the most popular data format in server/browser communication. It is light weight, human readable and easy to generate and parse.<br>Data from MySQL database can be easily converted into JSON format using PHP. The below example uses Sakila sample database that comes with standard MySQL installation. It fetches the first 3 rows of actor table into an associative array using mysqli_fetch_assoc(). Then the array is encoded into JSON using json_encode.', 'img.jpg', '2019-10-07 09:12:10', 0),
('Designing Bootstrap Signup Form with jQuery Validation', 'designing-bootstrap-signup-form-with-jquery-validation', 'Here Mudassar Ahmed Khan has explained how to build a Bootstrap HTML5 Registration (Signup) Form and perform validations using the numerous HTML5 in-built validations', 'img.jpg', '2019-10-08 19:42:03', 0);
